version: '3.7'
services:
  app:
    container_name: dockerized-react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src/
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
